### ISSUE TITLE
Error: Comentario mal formado

### ISSUE THREAD

**Issue by R4f4Lc** [iesgrancapitan-entornos/practica-5-github-issues-JavierGF00#1]
Los comentarios son con #
https://github.com/iesgrancapitan-entornos/practica-5-github-issues-JavierGF00/blob/f02f2784f6bb8cba3886cb1e6d6406e75a1771f8/holamundo.py#L1

**Comment by JavierGF00** [comment]
Muchas gracias, lo solucionaré de inmediato
